global:
  scrape_interval: 15s  # Collect metrics every 15 seconds

scrape_configs:
  - job_name: 'node_app'  # Define a job for monitoring the Node.js app
    static_configs:
      - targets: ['localhost:3000']  # Target the app's /metrics endpoint
