AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple serverless application using AWS Lambda
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
