apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2  # Two instances for redundancy
  template:
    spec:
      containers:
      - name: auth-service
        image: your-docker-repo/auth-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: secret-key
