# .github/workflows/deploy.yml

name: Deploy Flask App  # Pipeline name

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu as the build environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Pull the latest code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Define Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install required Python packages

      - name: Run tests
        run: |
          pytest tests/  # Run unit tests

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Deploy only if build succeeds
    steps:
      - name: Deploy to AWS Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Securely fetch AWS credentials
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          eb init -p python-3.9 my-flask-app --region us-east-1  # Initialize Elastic Beanstalk
          eb deploy  # Deploy the app
